apiVersion: v1
kind: Secret
metadata:   
  name: {{ .Values.cronJob.secret.name }}
type: Opaque
data:
  MONGO_DATABASE: {{ .Values.cronJob.MONGO_DATABASE }}
  MONGODB_ROOT_PASSWORD: {{ .Values.cronJob.MONGODB_ROOT_PASSWORD }}