apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-deployer
  namespace: default
spec:
  project: default
  source: 
    repoURL: https://github.com/oforisml/demo-crm-v5.git
    targetRevision: HEAD
    path: charts/argocd
    directory:
      jsonnet:
        tlas:
        - name: 'argocd-application'
          value: ''
  destination: 
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true