apiVersion: v1
kind: Secret
metadata:   
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.MONGO_INITDB_ROOT_USERNAME }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.MONGO_INITDB_ROOT_PASSWORD }}