apiVersion: v1
kind: Service
metadata:  
  name: {{ .Values.app.service.name }}
spec:
  selector:    
    app.name: {{ .Values.app.name }}
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP